name: Resume

on: [push]

jobs:
  resume_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: |
          touch .env
          echo CANDIDATE_URI=${{ secrets.CANDIDATE_URI }} >> .env
          npm run build

      - name: Deploy
        run: |
          apt-get update -qq && apt-get install -y -qq lftp
          lftp -c "set ftp:ssl-allow no; open -u ${{ secrets.DEPLOY_USERNAME }},${{ secrets.DEPLOY_PASSWD }} ${{ secrets.DEPLOY_HOSTNAME }}; mirror -Rnev ./build/ /test/ --ignore-time --parallel=10"
