name: Prod Deployment
on:
  push:
    branches:
      - 'master'

jobs:
  prod_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Build
        run: |
          touch .env
          echo CANDIDATE_URI=${{ secrets.CANDIDATE_URI }} >> .env
          npm run build

      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.DEPLOY_HOSTNAME }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWD }}
          local-dir: ./build/
          server-dir: prod/
